###############################################################
#  Generated by:      Cadence Encounter 09.11-s084_1
#  OS:                Linux x86_64(Host ID srge02.ecn.purdue.edu)
#  Generated on:      Tue Apr 26 17:10:56 2011
#  Command:           floorPlan -r 1.0 0.6 50 50 50 50
###############################################################

Version: 8

Head Box: 0.0000 0.0000 5103.9000 5080.9500
IO Box: 300.0000 0.0000 5103.9000 4780.9500
Core Box: 350.4000 51.0000 5053.9500 4731.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 350.4000 51.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_1 core 350.4000 81.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_2 core 350.4000 111.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_3 core 350.4000 141.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_4 core 350.4000 171.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_5 core 350.4000 201.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_6 core 350.4000 231.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_7 core 350.4000 261.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_8 core 350.4000 291.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_9 core 350.4000 321.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_10 core 350.4000 351.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_11 core 350.4000 381.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_12 core 350.4000 411.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_13 core 350.4000 441.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_14 core 350.4000 471.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_15 core 350.4000 501.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_16 core 350.4000 531.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_17 core 350.4000 561.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_18 core 350.4000 591.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_19 core 350.4000 621.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_20 core 350.4000 651.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_21 core 350.4000 681.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_22 core 350.4000 711.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_23 core 350.4000 741.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_24 core 350.4000 771.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_25 core 350.4000 801.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_26 core 350.4000 831.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_27 core 350.4000 861.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_28 core 350.4000 891.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_29 core 350.4000 921.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_30 core 350.4000 951.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_31 core 350.4000 981.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_32 core 350.4000 1011.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_33 core 350.4000 1041.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_34 core 350.4000 1071.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_35 core 350.4000 1101.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_36 core 350.4000 1131.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_37 core 350.4000 1161.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_38 core 350.4000 1191.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_39 core 350.4000 1221.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_40 core 350.4000 1251.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_41 core 350.4000 1281.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_42 core 350.4000 1311.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_43 core 350.4000 1341.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_44 core 350.4000 1371.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_45 core 350.4000 1401.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_46 core 350.4000 1431.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_47 core 350.4000 1461.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_48 core 350.4000 1491.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_49 core 350.4000 1521.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_50 core 350.4000 1551.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_51 core 350.4000 1581.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_52 core 350.4000 1611.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_53 core 350.4000 1641.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_54 core 350.4000 1671.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_55 core 350.4000 1701.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_56 core 350.4000 1731.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_57 core 350.4000 1761.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_58 core 350.4000 1791.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_59 core 350.4000 1821.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_60 core 350.4000 1851.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_61 core 350.4000 1881.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_62 core 350.4000 1911.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_63 core 350.4000 1941.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_64 core 350.4000 1971.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_65 core 350.4000 2001.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_66 core 350.4000 2031.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_67 core 350.4000 2061.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_68 core 350.4000 2091.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_69 core 350.4000 2121.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_70 core 350.4000 2151.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_71 core 350.4000 2181.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_72 core 350.4000 2211.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_73 core 350.4000 2241.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_74 core 350.4000 2271.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_75 core 350.4000 2301.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_76 core 350.4000 2331.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_77 core 350.4000 2361.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_78 core 350.4000 2391.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_79 core 350.4000 2421.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_80 core 350.4000 2451.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_81 core 350.4000 2481.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_82 core 350.4000 2511.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_83 core 350.4000 2541.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_84 core 350.4000 2571.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_85 core 350.4000 2601.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_86 core 350.4000 2631.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_87 core 350.4000 2661.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_88 core 350.4000 2691.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_89 core 350.4000 2721.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_90 core 350.4000 2751.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_91 core 350.4000 2781.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_92 core 350.4000 2811.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_93 core 350.4000 2841.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_94 core 350.4000 2871.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_95 core 350.4000 2901.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_96 core 350.4000 2931.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_97 core 350.4000 2961.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_98 core 350.4000 2991.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_99 core 350.4000 3021.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_100 core 350.4000 3051.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_101 core 350.4000 3081.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_102 core 350.4000 3111.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_103 core 350.4000 3141.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_104 core 350.4000 3171.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_105 core 350.4000 3201.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_106 core 350.4000 3231.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_107 core 350.4000 3261.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_108 core 350.4000 3291.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_109 core 350.4000 3321.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_110 core 350.4000 3351.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_111 core 350.4000 3381.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_112 core 350.4000 3411.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_113 core 350.4000 3441.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_114 core 350.4000 3471.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_115 core 350.4000 3501.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_116 core 350.4000 3531.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_117 core 350.4000 3561.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_118 core 350.4000 3591.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_119 core 350.4000 3621.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_120 core 350.4000 3651.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_121 core 350.4000 3681.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_122 core 350.4000 3711.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_123 core 350.4000 3741.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_124 core 350.4000 3771.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_125 core 350.4000 3801.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_126 core 350.4000 3831.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_127 core 350.4000 3861.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_128 core 350.4000 3891.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_129 core 350.4000 3921.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_130 core 350.4000 3951.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_131 core 350.4000 3981.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_132 core 350.4000 4011.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_133 core 350.4000 4041.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_134 core 350.4000 4071.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_135 core 350.4000 4101.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_136 core 350.4000 4131.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_137 core 350.4000 4161.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_138 core 350.4000 4191.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_139 core 350.4000 4221.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_140 core 350.4000 4251.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_141 core 350.4000 4281.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_142 core 350.4000 4311.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_143 core 350.4000 4341.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_144 core 350.4000 4371.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_145 core 350.4000 4401.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_146 core 350.4000 4431.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_147 core 350.4000 4461.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_148 core 350.4000 4491.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_149 core 350.4000 4521.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_150 core 350.4000 4551.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_151 core 350.4000 4581.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_152 core 350.4000 4611.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_153 core 350.4000 4641.0000 N 1959 1 2.4000 0.0000
DefRow: ROW_154 core 350.4000 4671.0000 FS 1959 1 2.4000 0.0000
DefRow: ROW_155 core 350.4000 4701.0000 N 1959 1 2.4000 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: X 1.2000 2127 2.4000 1 3
Track: Y 1.5000 1694 3.0000 1 3
Track: Y 1.5000 1694 3.0000 1 2
Track: X 1.2000 2127 2.4000 1 2
Track: X 1.2000 2127 2.4000 1 1
Track: Y 1.5000 1694 3.0000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: Y 5081.1000 1 49.6500
GCellGrid: Y 78.4500 128 39.0000
GCellGrid: Y -0.1500 2 39.6000
GCellGrid: X 5104.0500 1 33.9000
GCellGrid: X 78.1500 129 39.0000
GCellGrid: X -0.1500 2 39.3000

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd -pwr
PhysicalNet: gnd -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val isAltLayer=val isPffGroup=val > #
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval coreToBottom=fval   #
#         pinSpacingNorth=val pinSpacingWest=val pinSpacingSouth=val      #
#         pinSpacingEast=val  blockedLayers=xval >       #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name"                    #
#                       pins=nr spacing=val isOptOrder=1 isAltLayer=1 >   #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num cell="name" >                       #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <Partition name="BENC" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=2 pinSpacingWest=2 pinSpacingSouth=2 pinSpacingEast=2 blockedLayers=0x7 >
	<PinLayer side="N" Metal2=yes />
	<PinLayer side="W" Metal3=yes />
	<PinLayer side="S" Metal2=yes />
	<PinLayer side="E" Metal3=yes />
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################
Instance: CLK__L4_I25 R0 1267.2000 2241.0000
Instance: CLK__L4_I24 MX 2630.4000 2571.0000
Instance: CLK__L4_I23 R0 2124.0000 2241.0000
Instance: CLK__L4_I22 MX 1624.8000 2571.0000
Instance: CLK__L4_I21 MX 1075.2000 3111.0000
Instance: CLK__L4_I20 MX 3343.2000 2751.0000
Instance: CLK__L4_I19 R0 4322.4000 2241.0000
Instance: CLK__L4_I18 MX 4303.2000 3111.0000
Instance: CLK__L4_I17 R0 4672.8000 4101.0000
Instance: CLK__L4_I16 R0 1485.6000 681.0000
Instance: CLK__L4_I15 MX 1557.6000 1911.0000
Instance: CLK__L4_I14 R0 2042.4000 1221.0000
Instance: CLK__L4_I13 MX 2068.8000 231.0000
Instance: CLK__L4_I12 R0 2325.6000 501.0000
Instance: CLK__L4_I11 R0 3247.2000 321.0000
Instance: CLK__L4_I10 R0 3487.2000 2061.0000
Instance: CLK__L4_I9 MX 4238.4000 1371.0000
Instance: CLK__L4_I8 R0 4442.4000 441.0000
Instance: CLK__L4_I7 MX 1288.8000 231.0000
Instance: CLK__L4_I6 MX 540.0000 351.0000
Instance: CLK__L4_I5 R0 736.8000 441.0000
Instance: CLK__L4_I4 MX 1219.2000 1611.0000
Instance: CLK__L4_I3 MX 3204.0000 1011.0000
Instance: CLK__L4_I2 MX 3012.0000 2091.0000
Instance: CLK__L4_I1 MX 3112.8000 1611.0000
Instance: CLK__L4_I0 R0 2539.2000 1761.0000
Instance: CLK__L3_I5 R0 2020.8000 2721.0000
Instance: CLK__L3_I4 MX 3964.8000 3171.0000
Instance: CLK__L3_I3 R0 1329.6000 1101.0000
Instance: CLK__L3_I2 R0 3554.4000 1221.0000
Instance: CLK__L3_I1 R0 1286.4000 1101.0000
Instance: CLK__L3_I0 R0 3513.6000 1221.0000
Instance: CLK__L2_I2 MX 2827.2000 3111.0000
Instance: CLK__L2_I1 R0 2476.8000 1101.0000
Instance: CLK__L2_I0 MX 2282.4000 1911.0000
Instance: CLK__L1_I0 MX 2719.2000 51.0000
Instance: U_0/FIESTELCLK__L2_I2 R0 1814.4000 2061.0000
Instance: U_0/FIESTELCLK__L2_I1 MX 3112.8000 2031.0000
Instance: U_0/FIESTELCLK__L2_I0 R0 1785.6000 2061.0000
Instance: U_0/FIESTELCLK__L1_I0 R0 2476.8000 2061.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][7] MX 847.2000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][7] R180 1000.8000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][7] MY 849.6000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][7] R0 1087.2000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][7] R0 352.8000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][7] MX 364.8000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][7] MY 364.8000 321.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][7] R0 364.8000 201.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][6] MX 861.6000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][6] MY 1060.8000 441.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][6] MX 787.2000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][6] R0 703.2000 561.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][6] MX 688.8000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][6] R0 489.6000 741.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][6] R0 364.8000 561.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][6] R0 364.8000 681.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][5] MX 1569.6000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][5] R0 1382.4000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][5] MX 1521.6000 231.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][5] R0 1540.8000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][5] MX 1879.2000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][5] R0 1708.8000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][5] R0 1965.6000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][5] MX 1728.0000 231.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][4] MY 2160.0000 441.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][4] MY 2028.0000 501.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][4] R0 1819.2000 561.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][4] R180 1872.0000 351.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][4] R0 2121.6000 561.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][4] R180 2167.2000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][4] R0 1855.2000 741.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][4] R0 2020.8000 741.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][3] R180 1272.0000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][3] MY 1296.0000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][3] MY 1233.6000 321.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][3] MY 1224.0000 81.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][3] MX 628.8000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][3] MX 700.8000 51.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][3] R180 636.0000 231.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][3] MX 703.2000 351.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][2] R0 1144.8000 501.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][2] MX 1159.2000 351.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][2] MY 1411.2000 501.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][2] R0 1372.8000 321.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][2] R0 1075.2000 561.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][2] R180 1075.2000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][2] MX 1368.0000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][2] MX 1149.6000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][1] MX 1728.0000 351.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][1] MY 1857.6000 321.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][1] R0 1584.0000 501.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][1] R0 1447.2000 321.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][1] R0 1557.6000 561.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][1] MX 1735.2000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][1] R0 1728.0000 741.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][1] MX 1447.2000 711.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[7][0] MX 974.4000 231.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[6][0] R180 1092.0000 351.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[5][0] R0 794.4000 321.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[4][0] R0 849.6000 441.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[3][0] MY 352.8000 501.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[2][0] R0 422.4000 501.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[1][0] MX 355.2000 351.0000
Instance: U_0/U_5/MAPPING/UFIFORAM/fiforeg_reg[0][0] R0 496.8000 321.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r1_reg[3] MY 2988.0000 441.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r1_reg[2] R180 2863.2000 351.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r1_reg[1] R0 2419.2000 201.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r1_reg[0] R180 2493.6000 51.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r2_reg[3] MY 2858.4000 441.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r2_reg[2] R180 2704.8000 351.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r2_reg[1] R180 2407.2000 231.0000
Instance: U_0/U_5/MAPPING/UWFC/wrptr_r2_reg[0] R0 2474.4000 81.0000
Instance: U_0/U_5/MAPPING/UWFC/full_flag_r_reg MX 2397.6000 711.0000
Instance: U_0/U_5/MAPPING/UWFC/waddr_reg[2] R180 2280.0000 351.0000
Instance: U_0/U_5/MAPPING/UWFC/waddr_reg[1] MY 2265.6000 321.0000
Instance: U_0/U_5/MAPPING/UWFC/waddr_reg[0] R180 2275.2000 231.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/binary_r_reg[0] MY 2260.8000 441.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/binary_r_reg[1] R180 2265.6000 711.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/binary_r_reg[2] MY 2402.4000 681.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/binary_r_reg[3] MY 2515.2000 561.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/gray_r_reg[3] R0 2630.4000 561.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/gray_r_reg[2] MY 2580.0000 501.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/gray_r_reg[1] R0 2505.6000 321.0000
Instance: U_0/U_5/MAPPING/UWFC/WPU1/gray_r_reg[0] R0 2560.8000 201.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r1_reg[3] R0 2707.2000 501.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r1_reg[2] MX 2568.0000 351.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r1_reg[1] MY 2620.8000 321.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r1_reg[0] R0 2594.4000 81.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r2_reg[3] MY 2728.8000 441.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r2_reg[2] R0 2733.6000 321.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r2_reg[1] MX 2580.0000 231.0000
Instance: U_0/U_5/MAPPING/URFC/rwptr_r2_reg[0] MX 2604.0000 51.0000
Instance: U_0/U_5/MAPPING/URFC/empty_flag_r_reg MX 2793.6000 51.0000
Instance: U_0/U_5/MAPPING/URFC/raddr_reg[2] MY 2265.6000 201.0000
Instance: U_0/U_5/MAPPING/URFC/raddr_reg[1] MY 2239.2000 81.0000
Instance: U_0/U_5/MAPPING/URFC/raddr_reg[0] R180 2263.2000 51.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/binary_r_reg[0] MX 2932.8000 51.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/binary_r_reg[1] R0 3132.0000 81.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/binary_r_reg[2] R0 3004.8000 201.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/binary_r_reg[3] R0 2988.0000 321.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/gray_r_reg[3] MX 2976.0000 351.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/gray_r_reg[2] R0 2858.4000 321.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/gray_r_reg[1] R0 2361.6000 81.0000
Instance: U_0/U_5/MAPPING/URFC/RPU1/gray_r_reg[0] MX 2376.0000 51.0000
Instance: U_0/U_0/state_reg[0] MY 2275.2000 1101.0000
Instance: U_0/U_0/state_reg[3] MX 2280.0000 951.0000
Instance: U_0/U_0/state_reg[1] MX 1836.0000 1011.0000
Instance: U_0/U_0/state_reg[2] MX 1807.2000 891.0000
Instance: U_0/U_1/rndCT_reg[0] MY 3271.2000 2901.0000
Instance: U_0/U_1/rndCT_reg[1] R0 3444.0000 2901.0000
Instance: U_0/U_1/compileCT_reg[3] MX 2976.0000 2751.0000
Instance: U_0/U_1/compileCT_reg[1] R0 2942.4000 2721.0000
Instance: U_0/U_1/compileCT_reg[2] MX 2863.2000 2691.0000
Instance: U_0/U_1/compileCT_reg[0] MX 2712.0000 2751.0000
Instance: U_0/U_1/rndCT_reg[2] MX 3295.2000 3171.0000
Instance: U_0/U_1/rndCT_reg[3] R180 3132.0000 3231.0000
Instance: U_0/U_1/rndCT_reg[4] MX 2848.8000 3111.0000
Instance: U_0/U_1/cD_ENABLE_reg MY 2616.0000 3021.0000
Instance: U_0/U_1/cData2_reg[7] MX 3028.8000 1671.0000
Instance: U_0/U_1/cData2_reg[6] R0 3036.0000 2361.0000
Instance: U_0/U_1/cData2_reg[5] MX 2707.2000 1671.0000
Instance: U_0/U_1/cData2_reg[4] MX 2844.0000 1551.0000
Instance: U_0/U_1/cData2_reg[3] MX 3141.6000 1551.0000
Instance: U_0/U_1/cData2_reg[2] MX 2707.2000 2571.0000
Instance: U_0/U_1/cData2_reg[1] MX 2676.0000 1551.0000
Instance: U_0/U_1/cData2_reg[0] MX 3204.0000 1611.0000
Instance: U_0/U_1/cData8_reg[7] MX 1368.0000 2751.0000
Instance: U_0/U_1/cData8_reg[6] R0 1824.0000 2721.0000
Instance: U_0/U_1/cData8_reg[5] MX 1557.6000 1431.0000
Instance: U_0/U_1/cData8_reg[4] MX 2160.0000 1611.0000
Instance: U_0/U_1/cData8_reg[3] R0 1560.0000 1821.0000
Instance: U_0/U_1/cData8_reg[2] MX 1850.4000 2031.0000
Instance: U_0/U_1/cData8_reg[1] R180 2020.8000 1551.0000
Instance: U_0/U_1/cData8_reg[0] MX 1416.0000 1611.0000
Instance: U_0/U_1/cData7_reg[7] MX 1708.8000 2451.0000
Instance: U_0/U_1/cData7_reg[6] MX 2294.4000 2331.0000
Instance: U_0/U_1/cData7_reg[5] MX 1444.8000 2451.0000
Instance: U_0/U_1/cData7_reg[4] MX 1951.2000 2451.0000
Instance: U_0/U_1/cData7_reg[3] R0 1413.6000 2061.0000
Instance: U_0/U_1/cData7_reg[2] MX 1497.6000 1911.0000
Instance: U_0/U_1/cData7_reg[1] MX 1692.0000 2091.0000
Instance: U_0/U_1/cData7_reg[0] MX 2251.2000 2031.0000
Instance: U_0/U_1/cData6_reg[7] MX 2882.4000 1611.0000
Instance: U_0/U_1/cData6_reg[6] MX 3273.6000 2451.0000
Instance: U_0/U_1/cData6_reg[5] MY 2577.6000 1881.0000
Instance: U_0/U_1/cData6_reg[4] R0 2613.6000 1761.0000
Instance: U_0/U_1/cData6_reg[3] MX 3439.2000 1611.0000
Instance: U_0/U_1/cData6_reg[2] MX 2601.6000 2451.0000
Instance: U_0/U_1/cData6_reg[1] MX 2548.8000 1671.0000
Instance: U_0/U_1/cData6_reg[0] R0 3470.4000 1821.0000
Instance: U_0/U_1/cData5_reg[7] MX 2546.4000 2331.0000
Instance: U_0/U_1/cData5_reg[6] R0 3487.2000 2241.0000
Instance: U_0/U_1/cData5_reg[5] R0 2707.2000 2361.0000
Instance: U_0/U_1/cData5_reg[4] MX 3036.0000 2091.0000
Instance: U_0/U_1/cData5_reg[3] MX 3208.8000 2031.0000
Instance: U_0/U_1/cData5_reg[2] R0 3429.6000 2061.0000
Instance: U_0/U_1/cData5_reg[1] MY 2613.6000 2061.0000
Instance: U_0/U_1/cData5_reg[0] MX 3355.2000 2331.0000
Instance: U_0/U_1/cData4_reg[7] MX 1442.4000 2691.0000
Instance: U_0/U_1/cData4_reg[6] MX 1675.2000 2691.0000
Instance: U_0/U_1/cData4_reg[5] R180 1670.4000 1431.0000
Instance: U_0/U_1/cData4_reg[4] R180 2100.0000 1611.0000
Instance: U_0/U_1/cData4_reg[3] R0 1442.4000 1761.0000
Instance: U_0/U_1/cData4_reg[2] R0 1665.6000 1761.0000
Instance: U_0/U_1/cData4_reg[1] MX 1720.8000 1551.0000
Instance: U_0/U_1/cData4_reg[0] MX 1574.4000 1671.0000
Instance: U_0/U_1/cData3_reg[7] R0 1557.6000 2241.0000
Instance: U_0/U_1/cData3_reg[6] R0 1869.6000 2361.0000
Instance: U_0/U_1/cData3_reg[5] MX 1432.8000 2571.0000
Instance: U_0/U_1/cData3_reg[4] R0 1526.4000 2361.0000
Instance: U_0/U_1/cData3_reg[3] R0 1432.8000 2241.0000
Instance: U_0/U_1/cData3_reg[2] MX 1521.6000 2211.0000
Instance: U_0/U_1/cData3_reg[1] MX 1531.2000 2091.0000
Instance: U_0/U_1/cData3_reg[0] MX 1965.6000 2211.0000
Instance: U_0/U_1/cData1_reg[7] MX 2760.0000 2091.0000
Instance: U_0/U_1/cData1_reg[6] MX 3345.6000 2091.0000
Instance: U_0/U_1/cData1_reg[5] MX 2848.8000 2331.0000
Instance: U_0/U_1/cData1_reg[4] MY 3040.8000 2061.0000
Instance: U_0/U_1/cData1_reg[3] MX 3055.2000 2031.0000
Instance: U_0/U_1/cData1_reg[2] MX 3343.2000 1911.0000
Instance: U_0/U_1/cData1_reg[1] R180 2760.0000 2031.0000
Instance: U_0/U_1/cData1_reg[0] MX 3045.6000 2211.0000
Instance: U_0/U_1/CompData2_reg[63] R180 2560.8000 2091.0000
Instance: U_0/U_1/CompData2_reg[62] R0 3516.0000 2061.0000
Instance: U_0/U_1/CompData2_reg[61] R180 2913.6000 2211.0000
Instance: U_0/U_1/CompData2_reg[60] MY 3004.8000 1881.0000
Instance: U_0/U_1/CompData2_reg[59] R0 3144.0000 1881.0000
Instance: U_0/U_1/CompData2_reg[58] R0 3465.6000 1881.0000
Instance: U_0/U_1/CompData2_reg[57] MY 2637.6000 1881.0000
Instance: U_0/U_1/CompData2_reg[56] R180 3312.0000 2211.0000
Instance: U_0/U_1/CompData2_reg[55] MX 3004.8000 1431.0000
Instance: U_0/U_1/CompData2_reg[54] MX 3132.0000 2331.0000
Instance: U_0/U_1/CompData2_reg[53] R180 2474.4000 1611.0000
Instance: U_0/U_1/CompData2_reg[52] MY 2800.8000 1401.0000
Instance: U_0/U_1/CompData2_reg[51] MX 3480.0000 1551.0000
Instance: U_0/U_1/CompData2_reg[50] R180 2539.2000 2451.0000
Instance: U_0/U_1/CompData2_reg[49] R180 2592.0000 1431.0000
Instance: U_0/U_1/CompData2_reg[48] R0 3439.2000 1761.0000
Instance: U_0/U_1/CompData2_reg[47] MX 1644.0000 2211.0000
Instance: U_0/U_1/CompData2_reg[46] R0 2152.8000 2241.0000
Instance: U_0/U_1/CompData2_reg[45] R180 1286.4000 2451.0000
Instance: U_0/U_1/CompData2_reg[44] MX 1560.0000 2571.0000
Instance: U_0/U_1/CompData2_reg[43] MY 1288.8000 2241.0000
Instance: U_0/U_1/CompData2_reg[42] R180 1447.2000 2091.0000
Instance: U_0/U_1/CompData2_reg[41] MX 1584.0000 2031.0000
Instance: U_0/U_1/CompData2_reg[40] MX 2035.2000 1911.0000
Instance: U_0/U_1/CompData2_reg[39] R180 1368.0000 2571.0000
Instance: U_0/U_1/CompData2_reg[38] R180 1574.4000 2751.0000
Instance: U_0/U_1/CompData2_reg[37] R180 1680.0000 1371.0000
Instance: U_0/U_1/CompData2_reg[36] MY 2064.0000 1401.0000
Instance: U_0/U_1/CompData2_reg[35] MY 1324.8000 1761.0000
Instance: U_0/U_1/CompData2_reg[34] MX 1730.4000 1671.0000
Instance: U_0/U_1/CompData2_reg[33] MX 1742.4000 1371.0000
Instance: U_0/U_1/CompData2_reg[32] MY 1485.6000 1401.0000
Instance: U_0/U_1/CompData2_reg[31] MY 2433.6000 2241.0000
Instance: U_0/U_1/CompData2_reg[30] R180 3782.4000 2091.0000
Instance: U_0/U_1/CompData2_reg[29] MX 2630.4000 2331.0000
Instance: U_0/U_1/CompData2_reg[28] R180 2848.8000 2091.0000
Instance: U_0/U_1/CompData2_reg[27] MY 3290.4000 1881.0000
Instance: U_0/U_1/CompData2_reg[26] MX 3643.2000 1911.0000
Instance: U_0/U_1/CompData2_reg[25] MX 2407.2000 2031.0000
Instance: U_0/U_1/CompData2_reg[24] MY 3465.6000 2361.0000
Instance: U_0/U_1/CompData2_reg[23] MX 2985.6000 1551.0000
Instance: U_0/U_1/CompData2_reg[22] R180 3427.2000 2511.0000
Instance: U_0/U_1/CompData2_reg[21] MY 2474.4000 1761.0000
Instance: U_0/U_1/CompData2_reg[20] R180 2546.4000 1551.0000
Instance: U_0/U_1/CompData2_reg[19] MX 3631.2000 1551.0000
Instance: U_0/U_1/CompData2_reg[18] MY 2433.6000 2361.0000
Instance: U_0/U_1/CompData2_reg[17] R180 2462.4000 1431.0000
Instance: U_0/U_1/CompData2_reg[16] R0 3631.2000 1761.0000
Instance: U_0/U_1/CompData2_reg[15] R0 1728.0000 2361.0000
Instance: U_0/U_1/CompData2_reg[14] MX 2260.8000 2211.0000
Instance: U_0/U_1/CompData2_reg[13] MY 1401.6000 2361.0000
Instance: U_0/U_1/CompData2_reg[12] MX 1977.6000 2571.0000
Instance: U_0/U_1/CompData2_reg[11] R180 1372.8000 2091.0000
Instance: U_0/U_1/CompData2_reg[10] R180 1430.4000 1911.0000
Instance: U_0/U_1/CompData2_reg[9] MX 1670.4000 1911.0000
Instance: U_0/U_1/CompData2_reg[8] R180 2335.2000 1911.0000
Instance: U_0/U_1/CompData2_reg[7] R180 1447.2000 2751.0000
Instance: U_0/U_1/CompData2_reg[6] R180 1728.0000 2751.0000
Instance: U_0/U_1/CompData2_reg[5] MX 1531.2000 1371.0000
Instance: U_0/U_1/CompData2_reg[4] MX 2167.2000 1431.0000
Instance: U_0/U_1/CompData2_reg[3] MY 1372.8000 1821.0000
Instance: U_0/U_1/CompData2_reg[2] MX 1956.0000 1911.0000
Instance: U_0/U_1/CompData2_reg[1] MY 1879.2000 1401.0000
Instance: U_0/U_1/CompData2_reg[0] R180 1411.2000 1431.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[0] MX 1368.0000 1371.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[0] MY 1161.6000 1401.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[15] MY 1836.0000 2241.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[15] MX 1708.8000 2211.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[29] R180 2539.2000 2211.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[29] R180 2690.4000 2211.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[9] R180 1730.4000 1911.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[9] MY 1548.0000 1881.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[28] MX 2846.4000 1911.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[28] MY 2721.6000 1881.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[23] R180 2832.0000 1371.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[23] R180 3004.8000 1371.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[2] MY 1984.8000 1761.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[2] MX 1836.0000 1671.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[17] MY 2287.2000 1341.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[17] MY 2409.6000 1221.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[6] MX 1665.6000 2871.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[6] MX 1516.8000 2871.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[25] R0 2337.6000 1881.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[25] MY 2460.0000 1881.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[4] R180 2121.6000 1371.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[4] R0 1965.6000 1341.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[11] MY 1161.6000 2061.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[11] MX 1224.0000 2091.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[18] MY 2248.8000 2361.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[18] R180 2136.0000 2451.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[31] MX 2397.6000 2211.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[31] R180 2397.6000 2091.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[1] MY 1819.2000 1341.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[1] R0 1730.4000 1221.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[27] MY 3002.4000 1761.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[27] MY 2976.0000 1821.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[19] R180 3715.2000 1551.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[19] R180 3496.8000 1431.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[16] MX 3751.2000 1671.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[16] R180 3480.0000 1671.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[24] MY 3163.2000 2361.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[24] R180 3196.8000 2331.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[26] MY 3715.2000 1881.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[26] R0 3592.8000 1881.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[14] R180 2280.0000 2091.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[14] R180 2008.8000 2091.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[7] R180 1101.6000 2691.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[7] R180 1233.6000 2571.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[21] R180 2241.6000 1671.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[21] R180 2280.0000 1551.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[8] MY 2138.4000 1821.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[8] MY 1982.4000 1821.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[3] MY 1212.0000 1761.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[3] R180 1128.0000 1671.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[5] MY 1521.6000 1341.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[5] MY 1584.0000 1221.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[20] R180 2421.6000 1371.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[20] MY 2558.4000 1401.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[22] R180 3163.2000 2571.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[22] R180 3163.2000 2511.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[12] R180 1807.2000 2571.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[12] MX 1684.8000 2511.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[10] R180 1250.4000 1911.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[10] R0 1360.8000 1881.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[13] MY 1106.4000 2361.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[13] R180 1101.6000 2511.0000
Instance: U_0/U_2/CUR_ENC_RIGHT_reg[30] R180 3600.0000 2031.0000
Instance: U_0/U_2/CUR_ENC_LEFT_reg[30] MY 3588.0000 2061.0000
Instance: U_0/U_3/ENC_RIGHT_reg[1] MX 936.0000 1911.0000
Instance: U_0/U_3/ENC_RIGHT_reg[3] MX 931.2000 2031.0000
Instance: U_0/U_3/ENC_RIGHT_reg[5] R0 931.2000 2061.0000
Instance: U_0/U_3/ENC_RIGHT_reg[7] R180 952.8000 2091.0000
Instance: U_0/U_3/ENC_RIGHT_reg[9] R0 818.4000 1821.0000
Instance: U_0/U_3/ENC_RIGHT_reg[11] R0 933.6000 1881.0000
Instance: U_0/U_3/ENC_RIGHT_reg[13] MY 1048.8000 2061.0000
Instance: U_0/U_3/ENC_RIGHT_reg[15] R0 964.8000 2241.0000
Instance: U_0/U_3/ENC_RIGHT_reg[17] R0 1087.2000 2241.0000
Instance: U_0/U_3/ENC_RIGHT_reg[19] MX 1092.0000 2091.0000
Instance: U_0/U_3/ENC_RIGHT_reg[21] R180 1096.8000 2031.0000
Instance: U_0/U_3/ENC_RIGHT_reg[23] MY 1080.0000 1821.0000
Instance: U_0/U_3/ENC_RIGHT_reg[25] R0 933.6000 1821.0000
Instance: U_0/U_3/ENC_RIGHT_reg[27] MY 979.2000 1761.0000
Instance: U_0/U_3/ENC_RIGHT_reg[0] R180 1096.8000 1431.0000
Instance: U_0/U_3/ENC_RIGHT_reg[2] R0 1048.8000 1401.0000
Instance: U_0/U_3/ENC_RIGHT_reg[4] MY 931.2000 1401.0000
Instance: U_0/U_3/ENC_RIGHT_reg[6] MX 943.2000 1551.0000
Instance: U_0/U_3/ENC_RIGHT_reg[8] R180 931.2000 1371.0000
Instance: U_0/U_3/ENC_RIGHT_reg[10] R0 816.0000 1401.0000
Instance: U_0/U_3/ENC_RIGHT_reg[12] MX 816.0000 1371.0000
Instance: U_0/U_3/ENC_RIGHT_reg[14] R0 952.8000 1341.0000
Instance: U_0/U_3/ENC_RIGHT_reg[16] R180 931.2000 1611.0000
Instance: U_0/U_3/ENC_RIGHT_reg[18] R180 806.4000 1611.0000
Instance: U_0/U_3/ENC_RIGHT_reg[20] MX 828.0000 1551.0000
Instance: U_0/U_3/ENC_RIGHT_reg[22] MX 880.8000 1671.0000
Instance: U_0/U_3/ENC_RIGHT_reg[24] MX 991.2000 1671.0000
Instance: U_0/U_3/ENC_RIGHT_reg[26] MX 1106.4000 1611.0000
Instance: U_0/U_3/ENC_LEFT_reg[1] MX 3571.2000 1371.0000
Instance: U_0/U_3/ENC_LEFT_reg[3] MY 3235.2000 1341.0000
Instance: U_0/U_3/ENC_LEFT_reg[5] R0 3124.8000 1341.0000
Instance: U_0/U_3/ENC_LEFT_reg[7] MX 3124.8000 1371.0000
Instance: U_0/U_3/ENC_LEFT_reg[9] MY 3153.6000 1221.0000
Instance: U_0/U_3/ENC_LEFT_reg[11] MY 3124.8000 1101.0000
Instance: U_0/U_3/ENC_LEFT_reg[13] MY 3028.8000 1161.0000
Instance: U_0/U_3/ENC_LEFT_reg[15] R0 3019.2000 1221.0000
Instance: U_0/U_3/ENC_LEFT_reg[17] R0 3160.8000 1401.0000
Instance: U_0/U_3/ENC_LEFT_reg[19] R180 3208.8000 1431.0000
Instance: U_0/U_3/ENC_LEFT_reg[21] MX 3088.8000 1431.0000
Instance: U_0/U_3/ENC_LEFT_reg[23] MX 3384.0000 1431.0000
Instance: U_0/U_3/ENC_LEFT_reg[25] R0 3444.0000 1401.0000
Instance: U_0/U_3/ENC_LEFT_reg[27] R0 3578.4000 1401.0000
Instance: U_0/U_3/ENC_LEFT_reg[0] R0 2577.6000 1341.0000
Instance: U_0/U_3/ENC_LEFT_reg[2] MX 2700.0000 1371.0000
Instance: U_0/U_3/ENC_LEFT_reg[4] R0 2685.6000 1401.0000
Instance: U_0/U_3/ENC_LEFT_reg[6] MY 2728.8000 1761.0000
Instance: U_0/U_3/ENC_LEFT_reg[8] R0 2577.6000 1821.0000
Instance: U_0/U_3/ENC_LEFT_reg[10] MX 2666.4000 1911.0000
Instance: U_0/U_3/ENC_LEFT_reg[12] R0 3141.6000 1821.0000
Instance: U_0/U_3/ENC_LEFT_reg[14] MY 3302.4000 1821.0000
Instance: U_0/U_3/ENC_LEFT_reg[16] MX 3302.4000 1671.0000
Instance: U_0/U_3/ENC_LEFT_reg[18] R0 3283.2000 1401.0000
Instance: U_0/U_3/ENC_LEFT_reg[20] MX 3302.4000 1371.0000
Instance: U_0/U_3/ENC_LEFT_reg[22] MY 3345.6000 1341.0000
Instance: U_0/U_3/ENC_LEFT_reg[24] MY 2863.2000 1221.0000
Instance: U_0/U_3/ENC_LEFT_reg[26] MY 2700.0000 1341.0000
Instance: U_0/U_4/CUR_CNT_reg[0] MX 3160.8000 2691.0000
Instance: U_0/U_4/CUR_CNT_reg[1] R0 3439.2000 2721.0000
Instance: U_0/U_4/CUR_CNT_reg[2] MX 3451.2000 2751.0000
Instance: U_0/U_4/CUR_CNT_reg[3] R0 3160.8000 2721.0000
Instance: U_0/U_4/U9 MX 2265.6000 1911.0000
Instance: U_0/U_4/U10 MX 2308.8000 1911.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r1_reg[3] MY 604.8000 4581.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r1_reg[2] MY 720.0000 4581.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r1_reg[1] MY 736.8000 4341.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r1_reg[0] MY 1224.0000 4221.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r2_reg[3] MX 583.2000 4551.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r2_reg[2] R180 700.8000 4551.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r2_reg[1] MY 655.2000 4281.0000
Instance: U_1/U_5/MAPPING/URFC/rwptr_r2_reg[0] MY 957.6000 4221.0000
Instance: U_1/U_5/MAPPING/URFC/empty_flag_r_reg MX 523.2000 4071.0000
Instance: U_1/U_5/MAPPING/URFC/raddr_reg[2] R0 662.4000 4101.0000
Instance: U_1/U_5/MAPPING/URFC/raddr_reg[1] R0 636.0000 4221.0000
Instance: U_1/U_5/MAPPING/URFC/raddr_reg[0] R0 808.8000 4101.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/binary_r_reg[0] MX 369.6000 4071.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/binary_r_reg[1] MY 492.0000 4221.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/binary_r_reg[2] R0 350.4000 4341.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/binary_r_reg[3] MX 352.8000 4371.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/gray_r_reg[3] R0 511.2000 4461.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/gray_r_reg[2] MY 350.4000 4461.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/gray_r_reg[1] R0 609.6000 4341.0000
Instance: U_1/U_5/MAPPING/URFC/RPU1/gray_r_reg[0] R0 789.6000 4221.0000
Instance: U_1/U_8/ctr1_reg[0] R0 3444.0000 3021.0000
Instance: U_1/U_8/ctr1_reg[1] MX 3453.6000 3171.0000
Instance: U_2/U_0/HEADER_EN_reg MX 4778.4000 2331.0000
Instance: U_2/U_4/bluewait_reg[0] MY 4934.4000 3561.0000
Instance: U_2/U_4/cnt4_reg[2] MX 4759.2000 2751.0000
Instance: U_2/U_4/state_reg[0] MY 4180.8000 3381.0000
Instance: U_2/U_4/state_reg[2] R0 4303.2000 3561.0000
Instance: U_2/U_4/state_reg[1] MY 4605.6000 3621.0000
Instance: U_2/U_4/cnt2_reg[0] MY 4478.4000 2721.0000
Instance: U_2/U_4/cnt2_reg[1] R180 4452.0000 2751.0000
Instance: U_2/U_4/bluewait_reg[1] MX 4785.6000 2571.0000
Instance: U_2/U_4/bluewait_reg[2] MX 4761.6000 2451.0000
Instance: U_2/U_4/bluewait_reg[3] R180 4917.6000 3411.0000
Instance: U_2/U_4/bluewait_reg[4] R180 4843.2000 2691.0000
Instance: U_2/U_4/bluewait_reg[5] R0 4843.2000 3621.0000
Instance: U_2/U_4/cnt4_reg[1] R0 4728.0000 3621.0000
Instance: U_2/U_4/cnt4_reg[0] MX 4728.0000 2691.0000
Instance: U_2/U_2/swcnt_reg[0] R180 3729.6000 231.0000
Instance: U_2/U_2/swcnt_reg[1] R180 3748.8000 51.0000
Instance: U_2/U_2/swcnt_reg[14] R0 3285.6000 321.0000
Instance: U_2/U_2/state_reg[0] R0 4010.4000 441.0000
Instance: U_2/U_2/swcnt_reg[2] MX 3631.2000 51.0000
Instance: U_2/U_2/swcnt_reg[3] R180 3720.0000 711.0000
Instance: U_2/U_2/swcnt_reg[4] MX 3609.6000 711.0000
Instance: U_2/U_2/swcnt_reg[5] MX 3439.2000 351.0000
Instance: U_2/U_2/swcnt_reg[6] MX 3124.8000 351.0000
Instance: U_2/U_2/swcnt_reg[7] R0 3429.6000 561.0000
Instance: U_2/U_2/swcnt_reg[8] R0 3124.8000 501.0000
Instance: U_2/U_2/swcnt_reg[9] R0 3230.4000 741.0000
Instance: U_2/U_2/swcnt_reg[10] R0 3343.2000 741.0000
Instance: U_2/U_2/swcnt_reg[11] MX 3312.0000 51.0000
Instance: U_2/U_2/swcnt_reg[12] R0 3132.0000 321.0000
Instance: U_2/U_2/swcnt_reg[13] MX 3523.2000 51.0000
Instance: U_2/U_2/cnt32_reg[0] R0 4334.4000 561.0000
Instance: U_2/U_2/cnt8_reg[3] MX 4046.4000 951.0000
Instance: U_2/U_2/state_reg[2] R0 3864.0000 81.0000
Instance: U_2/U_2/state_reg[1] MY 4036.8000 321.0000
Instance: U_2/U_2/cnt8_reg[0] MX 4300.8000 831.0000
Instance: U_2/U_2/cnt8_reg[1] R0 4322.4000 681.0000
Instance: U_2/U_2/cnt8_reg[2] MX 4334.4000 951.0000
Instance: U_2/U_2/cnt32_reg[5] MX 3897.6000 51.0000
Instance: U_2/U_2/cnt32_reg[1] MX 4300.8000 351.0000
Instance: U_2/U_2/cnt32_reg[2] MX 4303.2000 51.0000
Instance: U_2/U_2/cnt32_reg[3] R0 4161.6000 501.0000
Instance: U_2/U_2/cnt32_reg[4] MX 4180.8000 51.0000
Instance: U_2/U_2/READ_EN_reg MX 4188.0000 951.0000
Instance: U_2/U_1/waitcnt_reg[0] R180 4600.8000 351.0000
Instance: U_2/U_1/waittx_reg MX 4452.0000 1011.0000
Instance: U_2/U_1/waitcnt_reg[16] R0 4473.6000 681.0000
Instance: U_2/U_1/waitcnt_reg[1] R0 4473.6000 561.0000
Instance: U_2/U_1/waitcnt_reg[2] MX 4452.0000 231.0000
Instance: U_2/U_1/waitcnt_reg[3] MX 4459.2000 51.0000
Instance: U_2/U_1/waitcnt_reg[4] MX 4600.8000 51.0000
Instance: U_2/U_1/waitcnt_reg[5] MX 4617.6000 231.0000
Instance: U_2/U_1/waitcnt_reg[6] R180 4778.4000 51.0000
Instance: U_2/U_1/waitcnt_reg[7] MX 4917.6000 51.0000
Instance: U_2/U_1/waitcnt_reg[8] MY 4759.2000 441.0000
Instance: U_2/U_1/waitcnt_reg[9] R0 4898.4000 321.0000
Instance: U_2/U_1/waitcnt_reg[10] R0 4903.2000 561.0000
Instance: U_2/U_1/waitcnt_reg[11] R0 4903.2000 741.0000
Instance: U_2/U_1/waitcnt_reg[12] MX 4929.6000 951.0000
Instance: U_2/U_1/waitcnt_reg[13] R180 4778.4000 1011.0000
Instance: U_2/U_1/waitcnt_reg[14] MX 4617.6000 711.0000
Instance: U_2/U_1/waitcnt_reg[15] MY 4629.6000 681.0000
Instance: U_2/U_1/ENCODE_EN_reg R180 4492.8000 891.0000
Instance: U_2/U_6/bluewait_reg[12] MX 4620.0000 4551.0000
Instance: U_2/U_6/bluewait_reg[3] R0 4778.4000 3921.0000
Instance: U_2/U_6/bluewait_reg[0] R0 4658.4000 4581.0000
Instance: U_2/U_6/bluewait_reg[1] R0 4776.0000 4581.0000
Instance: U_2/U_6/bluewait_reg[2] R0 4749.6000 4341.0000
Instance: U_2/U_6/bluewait_reg[4] MX 4929.6000 4071.0000
Instance: U_2/U_6/bluewait_reg[5] R0 4905.6000 3681.0000
Instance: U_2/U_6/bluewait_reg[6] R0 4744.8000 3681.0000
Instance: U_2/U_6/bluewait_reg[7] R0 4612.8000 3681.0000
Instance: U_2/U_6/bluewait_reg[8] MX 4632.0000 3831.0000
Instance: U_2/U_6/bluewait_reg[9] R0 4617.6000 4041.0000
Instance: U_2/U_6/bluewait_reg[10] R0 4903.2000 4281.0000
Instance: U_2/U_6/bluewait_reg[11] R0 4898.4000 4581.0000
Instance: U_2/U_6/txbuff_reg[1] R0 4480.8000 4341.0000
Instance: U_2/U_6/txbuff_reg[2] R0 4545.6000 4581.0000
Instance: U_2/U_6/txbuff_reg[3] R0 4480.8000 4461.0000
Instance: U_2/U_6/txbuff_reg[4] R0 4336.8000 4221.0000
Instance: U_2/U_6/txbuff_reg[5] R0 4336.8000 4341.0000
Instance: U_2/U_6/txbuff_reg[6] R0 4310.4000 4581.0000
Instance: U_2/U_6/txbuff_reg[7] MY 4425.6000 4581.0000
Instance: U_2/U_6/DATAOUT_reg MX 4490.4000 3771.0000
Instance: U_2/U_6/cnt8_reg[0] MY 4480.8000 4221.0000
Instance: U_2/U_6/cnt8_reg[1] MY 4480.8000 4041.0000
Instance: U_2/U_6/cnt8_reg[2] R0 4315.2000 4101.0000
Instance: U_2/U_6/stop_reg MY 4336.8000 3921.0000
Instance: U_4/icnt8_reg[0] MY 4010.4000 1821.0000
Instance: U_4/icnt8_reg[2] MX 4012.8000 2031.0000
Instance: U_4/state_reg[1] MX 4188.0000 1911.0000
Instance: U_4/state_reg[0] R0 4188.0000 1821.0000
Instance: U_4/cnt8_reg[0] MX 4617.6000 1671.0000
Instance: U_4/cnt8_reg[1] MX 4761.6000 1911.0000
Instance: U_4/cnt8_reg[2] MX 4771.2000 1671.0000
Instance: U_4/icnt8_reg[1] MX 3868.8000 1911.0000
Instance: U_4/WADDR_reg[0] MY 4821.6000 2361.0000
Instance: U_4/WADDR_reg[1] MX 4154.4000 3171.0000
Instance: U_4/WADDR_reg[2] MX 4010.4000 3111.0000
Instance: U_4/WADDR_reg[3] MX 3854.4000 3171.0000
Instance: U_4/WADDR_reg[4] MX 3715.2000 3111.0000
Instance: U_4/WADDR_reg[5] R0 3592.8000 3021.0000
Instance: U_4/WADDR_reg[6] R180 3484.8000 2511.0000
Instance: U_4/WADDR_reg[7] R0 3592.8000 2241.0000
Instance: U_4/WADDR_reg[8] MX 3897.6000 2031.0000
Instance: U_4/WADDR_reg[9] R180 4334.4000 2091.0000
Instance: U_4/WADDR_reg[10] R180 4629.6000 2031.0000
Instance: U_4/WADDR_reg[11] MY 4776.0000 2061.0000
Instance: U_4/RADDR_reg[0] MY 4706.4000 2361.0000
Instance: U_4/PRADDR_reg[0] R180 4459.2000 2451.0000
Instance: U_4/PRADDR_reg[1] R180 4375.2000 2571.0000
Instance: U_4/PRADDR_reg[2] MX 4092.0000 2571.0000
Instance: U_4/PRADDR_reg[3] MX 4012.8000 2691.0000
Instance: U_4/PRADDR_reg[4] MX 3895.2000 2691.0000
Instance: U_4/PRADDR_reg[5] MX 3820.8000 2571.0000
Instance: U_4/PRADDR_reg[6] MX 3748.8000 2451.0000
Instance: U_4/PRADDR_reg[7] R0 3748.8000 2361.0000
Instance: U_4/PRADDR_reg[8] MX 3897.6000 2331.0000
Instance: U_4/PRADDR_reg[9] MY 4188.0000 2241.0000
Instance: U_4/PRADDR_reg[10] MY 4351.2000 2241.0000
Instance: U_4/PRADDR_reg[11] MY 4600.8000 2241.0000
Instance: U_4/RADDR_reg[11] MX 4778.4000 2211.0000
Instance: U_4/RADDR_reg[10] R0 4480.8000 2061.0000
Instance: U_4/RADDR_reg[1] R180 4334.4000 2871.0000
Instance: U_4/RADDR_reg[2] MY 4188.0000 2901.0000
Instance: U_4/RADDR_reg[3] R0 4034.4000 2961.0000
Instance: U_4/RADDR_reg[4] MY 3770.4000 2961.0000
Instance: U_4/RADDR_reg[5] R0 3568.8000 2901.0000
Instance: U_4/RADDR_reg[6] R0 3588.0000 2721.0000
Instance: U_4/RADDR_reg[7] R180 3568.8000 2331.0000
Instance: U_4/RADDR_reg[8] R0 3756.0000 2061.0000
Instance: U_4/RADDR_reg[9] R180 4046.4000 2211.0000

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x7

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .BENC20843.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: U24 PADFC 0.0000 4780.9500 NW R0 - 01
IO: U2 PADNC 0.0000 2390.5500 W R90 - 01
IO: U1 PADNC 0.0000 0.0000 W R90 - 01

##########################################################################
#  <IOPins>                                                              #
#    <Pin name="pin_name" type="clock|power|ground|analog"               #
#         status="covered|fixed|placed" is_special=1 >                   #
#      <Port>                                                            #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d />             #
#        <Via name="via_name" x=1 y=2 /> ...                             #
#        <Layer id=id spacing=1.2 drw=1.2>                               #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                           #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />          #
#        </Layer> ...                                                    #
#      </Port>  ...                                                      #
#      <Antenna model=num type="name" value=float_num layer=num /> ...   #
#    </Pin> ...                                                          #
#  </IOPins>                                                             #
##########################################################################

<IOPins>
  <Pin name="CLK" status="placed" >
    <Port>
      <Pref x=2720.4000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2719.9500 lly=0.0000 urx=2720.8500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[7]" status="placed" >
    <Port>
      <Pref x=2552.4000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2551.9500 lly=5080.0500 urx=2552.8500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[6]" status="placed" >
    <Port>
      <Pref x=2557.2000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2556.7500 lly=5080.0500 urx=2557.6500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[5]" status="placed" >
    <Port>
      <Pref x=2547.6000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2547.1500 lly=5080.0500 urx=2548.0500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[4]" status="placed" >
    <Port>
      <Pref x=2542.8000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2542.3500 lly=5080.0500 urx=2543.2500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[3]" status="placed" >
    <Port>
      <Pref x=2538.0000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2537.5500 lly=5080.0500 urx=2538.4500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[2]" status="placed" >
    <Port>
      <Pref x=2569.2000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2568.7500 lly=5080.0500 urx=2569.6500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[1]" status="placed" >
    <Port>
      <Pref x=2533.2000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2532.7500 lly=5080.0500 urx=2533.6500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATA[0]" status="placed" >
    <Port>
      <Pref x=2574.0000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2573.5500 lly=5080.0500 urx=2574.4500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="D_MINUS" status="placed" >
    <Port>
      <Pref x=2895.6000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2895.1500 lly=5080.0500 urx=2896.0500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="D_PLUS" status="placed" >
    <Port>
      <Pref x=2924.4000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2923.9500 lly=5080.0500 urx=2924.8500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="READ_EN1" status="placed" >
    <Port>
      <Pref x=2509.2000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2508.7500 lly=5080.0500 urx=2509.6500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RENABLE" status="placed" >
    <Port>
      <Pref x=3068.4000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=3067.9500 lly=0.0000 urx=3068.8500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RST" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2533.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2532.7500 urx=5103.9000 ury=2534.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[11]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2047.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2046.7500 urx=5103.9000 ury=2048.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[10]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2014.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2013.7500 urx=5103.9000 ury=2015.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[9]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2134.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2133.7500 urx=5103.9000 ury=2135.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[8]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2020.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2019.7500 urx=5103.9000 ury=2021.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[7]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2254.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2253.7500 urx=5103.9000 ury=2255.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[6]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2494.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2493.7500 urx=5103.9000 ury=2495.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[5]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2794.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2793.7500 urx=5103.9000 ury=2795.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[4]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2800.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2799.7500 urx=5103.9000 ury=2801.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[3]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2827.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2826.7500 urx=5103.9000 ury=2828.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[2]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2767.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2766.7500 urx=5103.9000 ury=2768.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[1]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2773.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2772.7500 urx=5103.9000 ury=2774.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="ADDR[0]" status="placed" >
    <Port>
      <Pref x=5103.9000 y=2614.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=2613.7500 urx=5103.9000 ury=2615.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[7]" status="placed" >
    <Port>
      <Pref x=2528.4000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2527.9500 lly=5080.0500 urx=2528.8500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[6]" status="placed" >
    <Port>
      <Pref x=2578.8000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2578.3500 lly=5080.0500 urx=2579.2500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[5]" status="placed" >
    <Port>
      <Pref x=2523.6000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2523.1500 lly=5080.0500 urx=2524.0500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[4]" status="placed" >
    <Port>
      <Pref x=2583.6000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2583.1500 lly=5080.0500 urx=2584.0500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[3]" status="placed" >
    <Port>
      <Pref x=2518.8000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2518.3500 lly=5080.0500 urx=2519.2500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[2]" status="placed" >
    <Port>
      <Pref x=2588.4000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2587.9500 lly=5080.0500 urx=2588.8500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[1]" status="placed" >
    <Port>
      <Pref x=2514.0000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2513.5500 lly=5080.0500 urx=2514.4500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="DATAOUT[0]" status="placed" >
    <Port>
      <Pref x=2593.2000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2592.7500 lly=5080.0500 urx=2593.6500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="EMPTY_SRAM" status="placed" >
    <Port>
      <Pref x=2598.0000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2597.5500 lly=5080.0500 urx=2598.4500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[7]" status="placed" >
    <Port>
      <Pref x=927.6000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=927.1500 lly=0.0000 urx=928.0500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[6]" status="placed" >
    <Port>
      <Pref x=908.4000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=907.9500 lly=0.0000 urx=908.8500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[5]" status="placed" >
    <Port>
      <Pref x=1638.0000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=1637.5500 lly=0.0000 urx=1638.4500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[4]" status="placed" >
    <Port>
      <Pref x=1885.2000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=1884.7500 lly=0.0000 urx=1885.6500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[3]" status="placed" >
    <Port>
      <Pref x=1194.0000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=1193.5500 lly=0.0000 urx=1194.4500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[2]" status="placed" >
    <Port>
      <Pref x=1242.0000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=1241.5500 lly=0.0000 urx=1242.4500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[1]" status="placed" >
    <Port>
      <Pref x=1654.8000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=1654.3500 lly=0.0000 urx=1655.2500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="RDATA[0]" status="placed" >
    <Port>
      <Pref x=920.4000 y=0.0000 side=S width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=919.9500 lly=0.0000 urx=920.8500 ury=0.9000 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="r_enable_out" status="placed" >
    <Port>
      <Pref x=5103.9000 y=1822.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=1821.7500 urx=5103.9000 ury=1823.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="r_enable_s" status="placed" >
    <Port>
      <Pref x=5103.9000 y=1945.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=1944.7500 urx=5103.9000 ury=1946.2500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="r_error" status="placed" >
    <Port>
      <Pref x=2564.4000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2563.9500 lly=5080.0500 urx=2564.8500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="rcving" status="placed" >
    <Port>
      <Pref x=2790.0000 y=5080.9500 side=N width=0.9000 depth=0.9000 />
      <Layer id=2 >
        <Box llx=2789.5500 lly=5080.0500 urx=2790.4500 ury=5080.9500 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="w_enable_out" status="placed" >
    <Port>
      <Pref x=5103.9000 y=1810.5000 side=E width=1.5000 depth=1.5000 />
      <Layer id=3 >
        <Box llx=5102.4000 lly=1809.7500 urx=5103.9000 ury=1811.2500 />
      </Layer>
    </Port>
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="BENC">
	<prop name="CUT_ROWS" type=Int value=0 />
	<prop name="optimization_trialRoute_guide_flow" type=Int value=1 />
  </Design>
</Properties>

###########################################################$############################################################################################
#  GlobalNetConnection: <net_name> {-pin|-inst|-net} <base_name_pattern> -type {pgpin|net|tiehi|tielo} {-all|-module <name>|-region <box>} [-override] #
########################################################################################################################################################
GlobalNetConnection: vdd -pin vdd -type pgpin -all
GlobalNetConnection: gnd -pin gnd -type pgpin -all
GlobalNetConnection: vdd -type tiehi -all
GlobalNetConnection: gnd -type tielo -all
GlobalNetConnection: vdd -pin vdd -type pgpin -all -override
GlobalNetConnection: gnd -pin gnd -type pgpin -all -override

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
