Date:Mon Feb 28 01:57:21 AM EST 2011
Input command file generated by LEDA

#VERILOGCompiler	/package/eda/synopsys/leda-D-2010.03/amd64/bin/ve -M +no_lvs_env  -c -z -p2 -i -k95e -log /home/ecegrid/a/mg34/ece337/Lab6/leda-logs/compiler.log -full_log -snote +max_case+8 +max_casexz+8 -config_file /home/ecegrid/a/ece337/Class0.5u/.leda_config.tcl
#VHDLCompiler	/package/eda/synopsys/leda-D-2010.03/amd64/bin/v -M +no_lvs_env  -c -z -i -k93e -log /home/ecegrid/a/mg34/ece337/Lab6/leda-logs/compiler.log -full_log -snote -config_file /home/ecegrid/a/ece337/Class0.5u/.leda_config.tcl
#HOMELESS	LEDA_WORK
#Makefile-Name	LEDA_Makefile
#Makelibs-Name	LEDA_Makelibs
#Project-Name	/home/ecegrid/a/mg34/ece337/Lab6/leda.pro

#VHDLSuffixes
#End

#VHDLSuffixes
#End

#VERILOGSuffixes
#End
#Mappings
#End
#Files LEDA_WORK
#End

#VERILOGSuffixes
#End

#VHDLSuffixes
vhd -
vhdl -
#End
#Mappings
#End
#Files LEDA_WORK
   /home/ecegrid/a/mg34/ece337/Lab6/source/DECODE.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/EDGE_DETECT.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/EOP_DETECT.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/RCU.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/RCV_FIFO.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/SHIFT_REG.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/TIMER.vhd
   /home/ecegrid/a/mg34/ece337/Lab6/source/USB_RCVR.vhd
#End
#Resources
   IEEE $LEDA_PATH/amd64/resources/resource_93/IEEE 
   SNPS_EXT $LEDA_PATH/amd64/resources/resource_93/SNPS_EXT 
   STD $LEDA_PATH/amd64/resources/resource_93/STD 
   SYNOPSYS $LEDA_PATH/amd64/resources/resource_93/SYNOPSYS 
#End
